### ISSUE TITLE
ラベルの設定

### ISSUE THREAD

**Issue by fumsone** [setenvnet/titech-ueda#2]
@nakamototukasa @rinopo
ラベルを設定しようとしたのですが、自分のリポジトリではないためできませんでした。。
すみませんが、お手すきでご対応お願いしますー

**Comment by rinopo** [comment]
できました。

> ラベルを設定しようとしたのですが、自分のリポジトリではないためできませんでした。。

アクセス権も「Write」→「Owner」に変更しておきました。

---

なお、リポジトリ間でのissueラベルの統一は👇 のスクリプトを作ってやってます。
https://github.com/setenvnet/github-labels
